name: YoMino ESP32
on: push
jobs:
  build:
    name: Build YoMino for ESP32
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
